allows continues when aur/paru fails

diff --git a/.local/bin/update b/.local/bin/update
--- a/.local/bin/update
+++ b/.local/bin/update
@@ -32,7 +32,7 @@ check_mirrorlist() {
 pkg_update() {
   print_header "Upgrading Packages"
   if command -v paru &>/dev/null; then
-    paru -Syu --noconfirm
+    paru -Syu --noconfirm || echo "Paru failed, skipping..."
   else
     sudo pacman -Syu --noconfirm
   fi
